### ISSUE TITLE
Reading IMU values

### ISSUE THREAD

**Issue by KikiCS** [neurodigitaltechnologies/CSDK#1]
Hi! I'm using C++ SDK for Avatar VR.
When I use nd.getInertialValues method, I obtain only rawRotation quaternion values, while I get all zeros for rawAcceleration and rawAngularPosition. If I use nd.getAcceleration, I obtain one set of accelerations (x,y,z directions) but don't know how to select one of the IMUs as data source.
I would really appreciate if you added documentation about reading data from the IMUs.
Thank you!

**Comment by miguel-neurodigital** [comment]
Hi KikiCS!

Right now it is only possible to obtain rawRotation quaternion values from getInertialValues method.
The data obtained from getAcceleration it is only from IMU_0 (IMULOC_PALM). Which is available either for Avatar VR or Gloveone.

Thanks to you!
