### ISSUE TITLE
Problems with Hello World

### ISSUE THREAD

**Issue by KikiCS** [neurodigitaltechnologies/CSDK#2]
Hello, I see you uploaded a new version of the [page explaining C++ Hello world](http://docs.neurodigital.es/#/c++/hello_world) but I can not make it work now, while I was able to do it some months ago.
First: after the third #include I would expect "iostream" because otherwise my compiler is underlining every 'cout' statement as an error.
Second: I get an error on this line "res = nd.setActuatorPulse(static_cast(i), 0.8f, 1000, devices[0]);" which causes parentheses errors on every following line. I guess this is due to an update of the library and for this reason the function is currently being called in the wrong way.
Thank you in advance for your help.

**Comment by miguel-neurodigital** [comment]
Hi KikiCS, you're right, there are some errors in the code. Probably due to some bug on the plugin that we used to show the formatted code.

Now you can see it corrected, as well as the video showing how to configure the library.

Thank you and have a nice day!
